config/routes.rb
Avalanche::Application.routes.draw do
	get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	get "about" => "home#about", :as => "about"
	root :to => "home#index"
	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
	resources :contests do
		resources :participations, :only => [:new, :create, :destroy, :show]
		resources :ratings, :only => [:index, :create]
	end
	

end

app/models/contest.rb
class Contest < ActiveRecord::Base
	has_many :users, :through => :participations
	has_many :participations
	has_many :ratings
	attr_accessible :category, :desc, :ending, :name, :video
	
	def desc_preview(len)
		if self.desc.length < len
			self.desc
		else
			self.desc[0, len - 1] + "... "
		end
	end
	
	def contest_owner?(user)
		if user == nil
			false
		else
			user.id == self.user_id
		end
	end
	
	def all_submissions
		Participation.where("contest_id = ? AND user_id != ?", self, self.user_id).sort! { |p1,p2| p1.sort_by_score(p2) }
	end
	
	def submitted?(user)
		if user == nil
			false
		else
			Participation.where("contest_id = ? AND user_id = ?", self, user.id).blank? == false
		end
	end
	
	def curr_user_submission(user)
		Participation.where("contest_id = ? AND user_id = ?", self, user.id)[0]	
	end
	
	def delete
		Participation.where("contest_id = ?", self).each do |p|
			p.delete
		end
		self.destroy
	end
	
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

	def index
		@contests = Contest.all
	end

	def new
		@contest = Contest.new
		if !current_user
			redirect_to log_in_path
		end
	end
	
	def create
		if !current_user
			redirect_to log_in_path
		end
		contest = Contest.new(params[:contest])
		contest.user_id = current_user.id
		contest.save
		participation = Participation.new
		participation.contest_id = contest.id
		participation.user_id = current_user.id
		participation.donor = true
		participation.winner = false
		participation.save
		redirect_to contest
	end
	
	def show
		@contest = Contest.find(params[:id])
		@is_owner = @contest.contest_owner?(current_user)
		@has_submitted = @contest.submitted?(current_user)
		if @has_submitted
			@curr_user_submission = @contest.curr_user_submission(current_user)
		end
		@owner = User.find(@contest.user_id).name
		@video = embed_video(@contest)
		
		@submissions = @contest.all_submissions
		
	end
	
	def edit
		@contest = Contest.find(params[:id])
		if @contest.contest_owner?(current_user) == false
			redirect_to @contest
		end
	end
	
	def update
		contest = Contest.find(params[:id])
		if contest.contest_owner?(current_user) == false
			redirect_to contest
		end
		contest.update_attributes(params[:contest]) 
		redirect_to contest
	end
	
	def destroy
		contest = Contest.find(params[:id])
		if contest.contest_owner?(current_user) == false
			redirect_to contest
		end
		contest.delete
		redirect_to current_user
	end

end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/edit.html.erb
<div class="container inner shadow">
	<div class="row">
		<div class="span12">
			<div id="back"><%= link_to "&larr; Back".html_safe, @contest %></div>
			<div class="centered-text">
				<h1>Edit '<%= @contest.name %>'</h1>
				<hr>
			</div>
			<div class="centered-600">
				<%= form_for(@contest) do |form| %>
					<%= form.label :name, "Name of your challenge" %>
					<%= form.text_field :name, class: "span4" %>
					<%= form.label :category, "What kind of challenge is this?" %>
					<%= form.text_field :category %>
					<%= form.label :ending, "What day should your challenge end?" %>
					<%= form.text_field :ending, type: "date" %>
					<%= form.label :desc, "What should applicants know about your contest?" %>
					<%= form.text_area :desc, class: "span6" %>
					<%= form.label :video, "Provide the URL to an optional video prompt (youtube only, please):" %>
					<%= form.text_field :video, class: "span6" %>
					<br><br>
					<%= form.submit "Save changes" %> <span class="buttontext">or <%= link_to "cancel", @contest %> </span>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/contests/index.html.erb
<div class="container inner shadow">
	<div class="row">
		<div class="span12">
			<div class="centered-text">
				<h1>Browse Prompts</h1>
			</div>

			<% @contests.each do |contest| %>				
				<div class="contest animated">
					<%= link_to "", contest, class: "follow" %>
					<h3>
						<% if !contest %>
							Error!
						<% else %>
							<%= contest.name %>
						<% end %>
					</h3>
					<br>
					<%= content_tag(:iframe, "", :src => embed_video(contest), :class => "shadow") %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/contests/new.html.erb
<div class="container inner shadow">
	<div class="row">
		<div class="span12">
			<div id="back"><%= link_to "&larr; Back".html_safe, user_path(current_user) %></div>
			<div class="centered-text">
				<h1>Create a new challenge</h1>
				<hr>
			</div>
			<div class="centered-600">
				<%= form_for(@contest) do |form| %>
					<%= form.label :name, "Name of your challenge" %>
					<%= form.text_field :name, class: "span4" %>
					<%= form.label :category, "What kind of challenge is this?" %>
					<%= form.text_field :category %>
					<%= form.label :ending, "What day should your challenge end?" %>
					<%= form.text_field :ending, type: "date" %>
					<%= form.label :desc, "What should applicants know about your contest?" %>
					<%= form.text_area :desc, class: "span6" %>
					<%= form.label :video, "Provide the URL to an optional video prompt (youtube only, please):" %>
					<%= form.text_field :video, class: "span6" %>
					<br><br>
					<%= form.submit "Submit challenge" %> <span class="buttontext">or <%= link_to "cancel", current_user %> </span>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/contests/show.html.erb
<div class="participation-modal"></div>
<div class="participation-overlay">
	<button class="close">&times;</button>
	<% if current_user != nil %>
		<div class="rating-panel animated-fast"></div>
	<% end %>
	<iframe></iframe>
	<div class="nav-control go-left">
		<%= link_to "", contest_ratings_path(@contest), :remote => true %>
	</div>
	<div class="nav-control go-right">
		<%= link_to "", contest_ratings_path(@contest), :remote => true %>
	</div>
</div>
<div class="container" style="padding-top: 40px;">
	<div class="row">
		<div class="span12">			
			<% if @is_owner == true %>
				<div id="edit"><%= link_to "<i class='icon-pencil icon-white'></i>".html_safe, edit_contest_path(@contest), title: "Edit prompt" %></div>
			<% end %>
			
			<div class="row" style="position: relative;">
				<div class="span6">
					<div class="featured">
						<%= content_tag(:iframe, "", :src => embed_video(@contest), :style => "width: 420px; height: 315px;") %>
						<div class="featured-stand"></div>
						<div class="featured-counter"><h2 class="white">End date: <%= @contest.ending %></h2></div>
					</div>
				</div>
				<div class="span6 featured-wrap">
					<div class="featured-desc">
						<div class="centered-text">
							<h1><%= @contest.name %></h1>
						</div>
						<%= simple_format(@contest.desc) %>
						<hr class="white">
						<div class="centered-text">
							<% if @is_owner == false %>
								<% if @has_submitted == false %>
									<%= link_to "Apply", new_contest_participation_path(@contest), class: "button" %>
								<% else %>
									<%= link_to "View submission", contest_participation_path(@contest, @curr_user_submission), class: "button" %>
								<% end %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="span12">
			<br>
			<h1>Submissions</h1>
			<% @submissions.each do |submission| %>
				<%= content_tag :div, class: "submission animated" do %>
					<div><%= submission.submitter %><span class="dot">&middot;</span><%= submission.score %> point(s)</div>
					<%= content_tag :div, "", class: "follow", 'data-voted' => submission.voted?(current_user), 'data-score' => submission.score, :id => "c-" + @contest.id.to_s + "_" + submission.id.to_s %>
					<% if current_user != nil && current_user.id == submission.user_id %>
						<%= link_to contest_participation_path(@contest, submission), method: :delete, confirm: "Are you sure you want to your application to this contest?" do %>
							<%= content_tag :button, class: "close animated", type: "button" do %>
								&times;
							<% end %>
						<% end %>
					<% end %>
					<%= content_tag(:iframe, "", :src => embed_video(submission), :class => "shadow", :id => "v-" + @contest.id.to_s + "_" + submission.id.to_s, :style => "float: left; width: 263px; height: 197px;") %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>