config/routes.rb
Avalanche::Application.routes.draw do
	get "log_out" => "sessions#destroy", :as => "log_out"
	get "log_in" => "sessions#new", :as => "log_in"
	get "sign_up" => "users#new", :as => "sign_up"
	get "about" => "home#about", :as => "about"
	root :to => "home#index"
	resources :users
	resources :sessions, :only => [:new, :create, :destroy]
	resources :contests do
		resources :participations, :only => [:new, :create, :destroy, :show]
		resources :ratings, :only => [:index, :create]
	end
	

end

app/views/shared/_footer.html.erb
<div id="footer" class="shadow">
	<div class="container">
		<div class="row">
			<div class="span12">
				<div class="centered-text">
					<div class="left"><%= link_to "Home", root_path %> &middot; <%= link_to "About", about_path %> &middot; <a href="mailto:info@avalanche.io">Contact</a></div>
					<div class="right">&copy; Avalanche.io 2012</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--
<script type="text/javascript">
var sc_project=8465965; 
var sc_invisible=1; 
var sc_security="f0f0bcf0"; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost +
"statcounter.com/counter/counter.js'></"+"script>");</script>
<noscript><div class="statcounter"><a title="web statistics"
href="http://statcounter.com/" target="_blank"><img
class="statcounter"
src="https://c.statcounter.com/8465965/0/f0f0bcf0/1/"
alt="web statistics"></a></div></noscript>
-->

app/views/shared/_header.html.erb
<div id="header">	
	<div id="top" class="navbar">
		<div id="navback"></div>
		<div class="container" style="width: 940px; margin-left: auto; margin-right: auto; position: relative;">
			<% if current_user %>
				<div id="navname"><h2><%= current_user.name %></h2></div>
			<% end %>
			<div class="navbar-inner">				
				<div class="nav-collapse">
					<ul class="nav pull-left">	
						<li style="margin-right: 30px;">
							<%= link_to root_path do %>
								<%= content_tag :div, id: "header-logo" do %>
									<%= content_tag :h2 do %>
										<%= image_tag "Logo_Final.png", :size => "96x86" %>
									<% end %>
								<% end %>
							<% end %>
						</li>
					</ul>
					<ul id="rightnav" class="nav pull-right">
						<li>
							<%= link_to contests_path do %>
								<h2 class="animated-fast">Browse</h2>
							<% end %>
						</li>

						<li>
							<%= link_to new_contest_path do %>
								<h2 class="animated-fast">Submit a prompt</h2>
							<% end %>
						</li>
						<li>
							<!-- sign in or log in or log out -->
							<div id="user-nav">
								<% if current_user %>
									<h2><%= link_to "Profile", user_path(current_user), class: "animated-fast" %>/<%= link_to "Sign out", log_out_path %></h2>
								<% else %>
									<h2><%= link_to "Sign in", log_in_path %>/<%= link_to "Sign up", sign_up_path, class: "animated-fast" %></h2>
								<% end %>
							</div>
							<!-- end sign in or log in or log out -->
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="separator"></div>
</div>